### ISSUE TITLE
Cant run hikvisionctl on windows powershell

### ISSUE THREAD

**Issue by murphlmao** [jvmf1/hikvision-config#3]
When running in powershell, asks which app to open in. Opening in python/browser does nothing.

when running in cmd: 'hikvisionctl' is not recognized as an internal or external command,

**Comment by jvmf1** [comment]
Thats a windows problem because the script doesnt have the .py extension, if you go to ```C:\Users\User\AppData\Local\Programs\Python\Python3*\Scripts``` and run ```python hikvisionctl``` it will work fine. If you dont want to cd into this path everytime, just rename the ```hikvisionctl``` to ```hikvisionctl.py```. If you want to run it that way but without it opening another cmd window, please run ```cmd \k``` first and then ```hikvision.py [args]```

**Comment by jvmf1** [comment]
However Im pretty sure that renaming it will probably break pip from uninstalling or upgrading it
